### ISSUE TITLE
Merging Repos

### ISSUE THREAD

**Issue by borger** [hermanjustnu/scoop-emulators#10]
Hello @hermanjustnu great work!

I thought this repo was abandoned, that's why I created my own. If you agree, I'd like to merge mine with yours, it may not be too different other than the readme, would you be okay with that?

**Comment by borger** [comment]
I've created a PR: https://github.com/hermanjustnu/scoop-emulators/pull/11 review if you can, and let me know if it works for you, once complete, I'll remove my repo, and start contributing to yours...

**Comment by hermanjustnu** [comment]
Yes, thank you for your work with PR #7. Any other manifest contributions are welcomed.
