### ISSUE TITLE
cemu@1.18.2c: hash check failed

### ISSUE THREAD

**Issue by beatbrot** [hermanjustnu/scoop-emulators#23]
App:         emulators/cemu
URL:         https://cemu.info/releases/cemu_1.18.2.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    c716a6fb1c30ce1891ff5fb9b277744decadba534eddf230efca39f5c2cfd56c
Actual:      f8fe213a43d8a0ba63e52b7080b05c39b3922a6f82467587117c6642b0ff728d

**Comment by hermanjustnu** [comment]
Fixed in https://github.com/hermanjustnu/scoop-emulators/commit/d72cc362367e3709cc9d19d5287dc4ad2b00a281
