### ISSUE TITLE
Snes9x and FCEUX persist setting as folders

### ISSUE THREAD

**Issue by satorope** [hermanjustnu/scoop-emulators#3]
Snes9x persists snes9x.conf folder and cann't save settings.
FCEUX persists fceux.cfg folder and cann't save settings, too.

**Comment by borger** [comment]
I've sent a PR with the fix for this issue: https://github.com/hermanjustnu/scoop-emulators/pull/7

**Comment by borger** [comment]
You will very likely need to `scoop uninstall <package>` both of the packages and then reinstall with `scoop install <package>`. Do backup your existing configuration files, if applicable.

**Comment by hermanjustnu** [comment]
Fixed in PR #9
