### ISSUE TITLE
[Enhancement] Make Citra user folder persisted

### ISSUE THREAD

**Issue by RavenMacDaddy** [hermanjustnu/scoop-emulators#34]
Currently running the Citra-Canary branch.

The user folder does exist in persist, but since it's not linked, the emulator will still pick what's in the app folder, which means you always have to copy stuff back and forth to get everything set up after every update.

Hopefully this isn't complicated to fix.

Thank you in advance.

**Comment by hermanjustnu** [comment]
I think maybe you are using the [citra-canary](https://github.com/Calinou/scoop-games/blob/master/bucket/citra-canary.json) manifest from [scoop-games](https://github.com/Calinou/scoop-games)? We have a bit of an overlap between the two buckets...

**Comment by RavenMacDaddy** [comment]
It's listed as installed from your bucket, but should I post it there as well?

**Comment by hermanjustnu** [comment]
The manifest in scoop-games has persistence enabled. The manifest in scoop-emulators uses %APPDATA%. If you want persistance, reinstall the manifest from scoop-games.
