### ISSUE TITLE
Persist

### ISSUE THREAD

**Issue by satorope** [hermanjustnu/scoop-emulators#4]
Plese persist those.

# desmume-nightly

## Folders:
AviFiles
Battery
Cheats
Firmware
Lua
Roms
Screenshots
SramImportExport
States
StateSlots

## File:
desmume.ini

# mgba

## File:
config.ini

**Comment by borger** [comment]
I've sent a PR with the fix for this issue: https://github.com/hermanjustnu/scoop-emulators/pull/7

**Comment by hermanjustnu** [comment]
Fixed in PR #9
