### ISSUE TITLE
 retroarch@1.9.10_x86_64 Can't shim 'retroarch.exe': File doesn't exist.

### ISSUE THREAD

**Issue by satorope** [hermanjustnu/scoop-emulators#46]
Installing 'retroarch' (1.9.10) [64bit]
Loading RetroArch.7z from cache.
Checking hash of RetroArch.7z ... ok.
Extracting RetroArch.7z ... done.
Running pre-install script...
Linking ~\scoop\apps\retroarch\current => ~\scoop\apps\retroarch\1.9.10
Creating shim for 'retroarch'.
Can't shim 'retroarch.exe': File doesn't exist.

**Comment by hermanjustnu** [comment]
Fixed in #50
