### ISSUE TITLE
Backport updates from fork to this repo

### ISSUE THREAD

**Issue by beyondmeat** [hermanjustnu/scoop-emulators#56]
Hello @hermanjustnu,

I have been working on both scoop-games and a fork of this repo to fix up, normalize and standardize emu manifests.

I have many fixes and updates for manifests in this repo that will fix and close practically all of your open issues.

These updates have been tested in all stages (install, update, uninstall) and all of them are updated and working as my writing.

I would like to contribute my updates to this repo. Can I get push access to the repo or will you be able to merge in a PR relatively quicky? My changes will cause conflicts if the bot runs before my merge is approved.

Summary of changes:

* Fixes many broken manifests either not installing or stuck at old versions.
* Sorts the manifest files so they are all consistent
* Adds missing persist items
* Adds proper pre_install that will auto-enable portable mode for the app, and migrate data to the persist folder if needed.
* Adds/Updates license info and includes urls to the license.
* Various fixes to get auto-updates working
* Added dev variants to various apps
* all manifests pass schema validation

My changes should close all existing PRs and issues.

**Comment by hermanjustnu** [comment]
I've invited you as a collaborator. Please keep the manifests to emulators only. Thank you.

**Comment by beyondmeat** [comment]
all set. feel free to drop any you don't want.

**Comment by hermanjustnu** [comment]
Thanks!

**Comment by hermanjustnu** [comment]
Re: https://github.com/hermanjustnu/scoop-emulators/issues/57#issuecomment-1061238530

1. Not sure about the vsredist 2019, can you give an example of a commit where I reverted that?
2. Desmume is the same version you pointed out, but with a version prefix and build number. Scoop does not like just a commit id for version afaik.
3. This is an emulator bucket, PS3 system firmware nor any other firmware will not be in this bucket.
4. You asked to fix some of the PR:s and maybe add a manifest or two. My opinion is that that does not include complete refactoring the order of almost every manifest, changing build scripts and approach.
5. I am working on my own alternative Github action scripts, so it would conflict with the ones you "proposed".
6. The JSON sort order can't possibly be official, since `architecture` does not sort last in any of the repositories I checked.
7. Because of the changes I having problems tracking down why variables leak through multiple manifests while updating.

But anyway, thanks for your contribution.

**Comment by beyondmeat** [comment]
1. You will see it when looking at the diff on your reverts. 
2. afaik it doesn't matter, some may prefer the date. I just try to stick with what the app uses for the version then fallback to commit. However, having the date is useful to know how old the build is, so this is just preference.
3. True, but you have CemuHook and Betterjoy which are helper apps for emus, not really required but recommended. IMO It's just one less step a user needs to do to get ps3 emu working as that firmware is required by it. This one is up to you, but weird line to draw to allow a emu plugin but not emu firmware.
5.  You had lots of partial and outdated manifests. My only goal was to get your manifests to a known good state (p64 was a special case, I missed their redirect bs thanks for fixing that). Some of your manifests were either old and not updating or broken in other ways. For example, I either added missing persists or fixed them or updated  a post_install old way of handling file persists with a better way (creating the file on pre_install, then you dont need to backup/copy/move the files and other janky stuff). In other cases, it wasn't enabling portable mode for the emu, so I added that.
6. That sort order was pulled directly from scoops official contributing guidelines. architecture isn't listed in their sort order, which is interesting. I'm not against it being last, simply was just following https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md

At the very least, I hope it was somewhat useful for you and your bucket users. The nice thing about scoop is anyone can run their own bucket, especially now with the new github workflows making it easy and free

**Comment by hermanjustnu** [comment]
1. It would be easier if you could point out the example, but hey, searching works too. I could find one vcredist2015 suggests that were overlapping in our commits, and it was introduced by you: [b699427](https://github.com/hermanjustnu/scoop-emulators/commit/b699427d423c61261c6eabbc09e23ee7e8175f1e#diff-c45fe16ae6d8525dcb1066122497e65e7e346412649ee92f09cf9d0a291200b0R7) and re-ordered in [aaeff73](https://github.com/hermanjustnu/scoop-emulators/commit/aaeff737baf3f62e047ad389e47955f7e428c009#diff-c45fe16ae6d8525dcb1066122497e65e7e346412649ee92f09cf9d0a291200b0R30)
2. It does matter if Scoop does not detect the version change. If you check how [Compare-Version](https://github.com/ScoopInstaller/Scoop/blob/04b30de9dde613acec8bb0014b42f381f83e2ec9/lib/versions.ps1#L108) works, it should be clear that a commit ID is not a great choice for version number.
3. Yes, some exceptions to the emulator rule. But here is a perfect opportunity to create a scoop-firmware bucket, with suggests or depends to this or other emulator related scoop buckets.
4. Yes, and I was thankful that you stepped up and helped me get some of the updates in order. I was not just expecting a total overhaul. For the changed you made for persists and others; Perfect! Thank you!
5. It's nice that there are some guidelines. I would however have liked to be able to plan that activity separately, and not together with all the other changes.

**Comment by beyondmeat** [comment]
3. I like this idea, especially if more bios/firmware for other emus can be legally added like the ps3 firmware.
