### ISSUE TITLE
project64@3.0.1: Hash check failed

### ISSUE THREAD

**Issue by Brawl345** [hermanjustnu/scoop-emulators#57]
Hash check failed!
App:         emulators/project64
URL:         https://www.pj64-emu.com/download/project64-3-0-1-zip
First bytes: 60 33 68 79 67 84 89 80
Expected:    0cf95cbb70f33166258eff125f592bdf8534e8170af5f2b98a3d01b1516cead4
Actual:      2cea81ee09fcf66102afafdb98dc3669011b0112d570c4b1af8ecc5258e66b73

**Comment by Brawl345** [comment]
@hermanjustnu Hm this doesn't seem right. There is a download site which redirects and scoop downloads this. Is it even possible to bypass it?

**Comment by hermanjustnu** [comment]
I'm on it. It is possible. Fix coming during the day.

**Comment by beyondmeat** [comment]
@hermanjustnu I think the bot fix it?

**Comment by beyondmeat** [comment]
@hermanjustnu btw you can disable your bot now

**Comment by beyondmeat** [comment]
the workflow bot auto-fixed the hash, nice! can close

**Comment by Brawl345** [comment]
The hash `2cea81ee09fcf66102afafdb98dc3669011b0112d570c4b1af8ecc5258e66b73 ` is for the download page itself though, not the ZIP. Scoop downloads the HTML page, you can confirm it by opening the file from the cache folder.

**Comment by hermanjustnu** [comment]
No, it did not. It calculated the hash of "https://www.pj64-emu.com/download/project64-3-0-1-zip", which contains a javascript redirect (which Invoke-WebRequest will not follow).

To make it work, you need:

1. Dowload https://www.pj64-emu.com/public-releases
2. Regexp the page to find the zip, https://www.pj64-emu.com/download/project64-3-0-1-zip
3. Regexp that page to find the download url: https://www.pj64-emu.com/file/project64-3-0-0-5632-f83bee9/
4. Get the headers of that page to find the "real" filename for version parsing: Project64-3.0.1-5664-2df3434.zip
5. Output new version (`3.0.1-5664-2df3434`) and download url (`https://www.pj64-emu.com/file/project64-3-0-0-5632-f83bee9/`)
6. After that, hash calculations will work.

**Comment by Brawl345** [comment]
I think you need to add `#/dl.zip`  or something to the URL so that Scoop detects that it needs to extract it. It now downloads the correct version but doesn't extract it 😅

**Comment by hermanjustnu** [comment]
Oh, that last little thing I forgot. 😄 Fixing it

**Comment by Brawl345** [comment]
Now it works! Thank you!

**Comment by beyondmeat** [comment]
@hermanjustnu imo you reverted way too much. For example, some emus now depend on vsredist 2019 but you reverted back to 2015. you reverted desmume back to an old dead version. You took out the github actions (taken from the scoop main bucket) which IMO are useful. The sort order was reverted, not sure why since that was the scoop offical order.

It's your repo, do what you want of course.

**Comment by hermanjustnu** [comment]
@beyondmeat Answered in: https://github.com/hermanjustnu/scoop-emulators/issues/56#issuecomment-1061442419
