### ISSUE TITLE
[Request] Duckstation Preview

### ISSUE THREAD

**Issue by ppvnf** [hermanjustnu/scoop-emulators#73]
Please add preview version

https://github.com/stenzek/duckstation/releases/tag/preview

**Comment by ppvnf** [comment]
@hermanjustnu Thanks, but you've added the regular version. Preview version is this one: https://github.com/stenzek/duckstation/releases/download/preview/duckstation-windows-x64-release.zip

**Comment by hermanjustnu** [comment]
Thanks, a little bit too much copypasta, I forgot the autoupdate URL:s. Fixed now.

**Comment by ppvnf** [comment]
@hermanjustnu, I'm getting this error when trying to install it:

![Captura de tela 2022-10-25 231259](https://user-images.githubusercontent.com/73800734/197918426-7a2f5712-1bf4-4ff3-9647-2e7101a2a0d6.png)

**Comment by ppvnf** [comment]
Thanks! I "made" a blue icon for it:

[Blue Duck.zip](https://github.com/hermanjustnu/scoop-emulators/files/9890388/Blue.Duck.zip)
